before_script:
  - git remote add ssh://dokku@projects.multimediatechnology.at:5412/undercover -f

deploy:
  script:
      - git push dokku@projects.multimediatechnology.at:5412/undercover master -f
      - dokku run rails db:migrate
