image: ruby:2.3.3

before_script:
  - gem install bundler
  - bundle install
  - curl -sL https://deb.nodesource.com/setup_8.x | bash
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

run_project:
  script:
    - yarn install