image: ruby:2.3.3

stages:
 - build
 - deploy

build:
  stage: build
  before_script:
    - apt-get update
    - gem install bundler
    - curl -sL https://deb.nodesource.com/setup_8.x | bash
    - apt-get install nodejs
    - npm install -g yarn
    - apt-get install zip -y

  script:
    - bundle install
    - yarn install
    - zip -r -q data *

  artifacts:
    paths:
    - ./data.zip
    expire_in: 3 weeks

deploy:
  stage: deploy
  cache:
    paths:
    - node_modules
  before_script:
    - apt-get update
    - apt-get install openssh-client
    - eval $(ssh-agent -s)
    - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-add -l
    - ssh -o StrictHostKeyChecking=no pat@46.38.235.104 uptime
  script:
    - ssh pat@46.38.235.104 "screen -S undercover -X quit || true"
    - ssh pat@46.38.235.104 "rm -rf /var/www/html/dev_undercover/*"
    - scp -r ./data.zip pat@46.38.235.104:/var/www/html/dev_undercover/
    - ssh pat@46.38.235.104 "unzip -q /var/www/html/dev_undercover/data.zip -d /var/www/html/dev_undercover/"
    - TERM=vt100; export TERM
    - ssh -tt pat@46.38.235.104 "TERM=vt100; export TERM; cd /var/www/html/dev_undercover/; bundle install; screen -S undercover rails s"

