before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'projects.multimediatechnology.at' >> ~/.ssh/known_hosts
  - git remote add dokku ssh://dokku@projects.multimediatechnology.at:5412/undercover
  - cat ~/.ssh/known_hosts

stages:
  - deploy

deploy_to_dokku:
  stage: deploy
  script:
    - git push dokku master -f
    - dokku run rails db:migrate

