before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - chmod 700 ~/.ssh/id_rsa
  - ssh-add -l

  # - git remote add dokku ssh://dokku@projects.multimediatechnology.at:5412/undercover

stages:
  - deploy

deploy_to_dokku:
  stage: deploy
  script:
    - git push dokku master -f
    - dokku run rails db:migrate

