image: ruby:2.3.3

before_script:
  - gem install bundler
  - bundle install
  - curl -sL https://deb.nodesource.com/setup_8.x | bash
  - apt-get install nodejs
  - node -v
  - npm -v
  - npm install -g yarn
  - yarn install
  - apt-get install openssh-client

deploy:
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh -p22 pat@46.38.235.104 "mkdir undercover/_tmp"
    - scp -P22 -r pat@46.38.235.104:undercover/_tmp
    - ssh -p22 pat@46.38.235.104 "mv undercover/_tmp /var/www/html/dev_undercover/"
    - ssh -p22 pat@46.38.235.104 "rm -rf undercover/_tmp"