image: ruby:2.3.3

stages:
 - build
 - test
 - deploy

before_script:
  - gem install bundler
  - bundle install
  - curl -sL https://deb.nodesource.com/setup_8.x | bash
  - apt-get install nodejs
  - npm install -g yarn
  - apt-get install openssh-client
  - apt-get install rsync -y
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh-add -l
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh -o StrictHostKeyChecking=no pat@46.38.235.104 uptime

cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - yarn install

deploy:
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install zip -y unzip -y
  script:
    - zip -r data *
    - rsync -a -o ./data.zip pat@46.38.235.104:/var/www/html/_tmp/
    - ssh -o StrictHostKeyChecking=no pat@46.38.235.104 "unzip -o /var/www/html/_tmp/data.zip"
