# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Role.destroy_all
Role.create(name: 'Godfather',
            party: 'Mafia',
            active: 'corrupt',
            passive: 'immunity',
            power: '4',
            rank: '',
            image: '/images/mafia/godfather_mafia.jpg',
            goal: 'Bear down all townsmen.',
            lore: 'Before turning to a career in organized crime, the Godfather worked as a high school chemistry teacher. After discovering his talents in the manufacturing of white sand, he decided to move up the career ladder. Soon he took over the godfatherhood of the local mob and helped the Organisation rise to new glory, while still managing to hide his profession from his four children.',
            punchline: 'After discovering his talents in the manufacturing of white sand, he decided to move up the career ladder.',
            active_text: 'Money will change a player’s mind. Your target will join the mafia.',
            passive_text: 'This character cannot be converted by the president.',
            text_success: 'Corruption! Money changed somebody’s mind.',
            text_fail: 'A citizen declined a whole bunch of money.')
Role.create(name: 'Bodyguard',
            party: 'Mafia',
            active: 'blackmail',
            passive: 'protect',
            power: '3',
            rank: '',
            image: '/images/mafia/bodyguards_mafia.jpg',
            goal: 'Bear down all townsmen.',
            lore: 'As the city’s youngest boxer, he managed to claim the prized “King in the Ring” title. While continuing his professional sports career, he also took up a freelance job as bodyguard in the Organisation. He enjoys threatening civiliants to gather information, where just like in his work life, he doesn’t shy away from sullying his hands.',
            punchline: 'He enjoys threatening civiliants to gather information, where just like in his work life, he doesn’t shy away from sullying his hands.',
            active_text: 'Threaten somebody to get information about a player’s real face.',
            passive_text: 'This character protects its leader with his life. If the godfather would die, you will die instead.',
            text_success: 'Threatened by a criminal, a player revealed its role.',
            text_fail: 'Blackmailing failed')
Role.create(name: 'Enforcer',
            party: 'Mafia',
            active: 'shoot',
            passive: nil,
            power: '2',
            rank: '',
            image: '/images/mafia/enforcer_mafia.jpg',
            goal: 'Bear down all townsmen.',
            lore: 'Became self-employed at 18 years old. After initially having trouble keeping clients, she joined the organisation and managed to establish a renowned reputation with their help. Her clients especially value her thoroughness and goal oriented work ethic.',
            punchline: 'Her clients especially value her thoroughness and goal oriented work ethic.',
            active_text: 'Strike down somebody to take them out of the game.',
            passive_text: '',
            text_success: 'R.I.P. Someone lies dead on the street.',
            text_fail: 'Shooting failed.')
Role.create(name: 'Beagle Boy',
            party: 'Mafia',
            active: 'free',
            passive: nil,
            power: '1',
            rank: '',
            image: '/images/mafia/beagleboy_mafia.jpg',
            goal: 'Bear down all townsmen.',
            lore: 'His career in the organisation began very early. After three years he already finished school and since then focused completely on his professional life. His greatest pride is his vast collection of locks – to most of which he always has the right key handy.',
            punchline: 'His greatest pride is his vast collection of locks – to most of which he always has the right key handy.',
            active_text: 'Rescue a player from prison. Freedom!',
            passive_text: '',
            text_success: 'Sneaky, sneaky. A prisoner is freed.',
            text_fail: 'Freeing the prisoner failed.')
Role.create(name: 'President',
            party: 'Town',
            active: 'convert',
            passive: 'immunity',
            power: '4',
            rank: '',
            image: '/images/town/president_town.jpg',
            goal: 'Bear down all henchmen of the mafia.',
            lore: 'As a mother of four, she is used to giving orders. That also comes in very handy at her job as president, a position she has held for over two decades. Some claim her party’s good work is the reason for their dominant position in the government. Most experts, however, agree that it’s a result of the country’s one-party system.',
            punchline: 'Some claim her party’s good work is the reason for their dominant position in the government.',
            active_text: 'Your rhetorical skills will change your target’s mind. Your target will join your forces',
            passive_text: 'This character cannot be corrupted by the godfather.',
            text_success: 'Successful convert.',
            text_fail: 'Converting failed.')
Role.create(name: 'Chief',
            party: 'Town',
            active: 'imprison',
            passive: 'protect',
            power: '3',
            rank: '',
            image: '/images/town/chief_town.jpg',
            goal: 'Bear down all henchmen of the mafia.',
            lore: 'He’s not a dirty cop – except when he soils his shirts with the donuts he’s eating constantly. Initially he wanted to become a musician, but sadly the band he founded in his youth with four friends broke up. Since then he focusses thoroughly on delivering justice to the land.',
            punchline: 'Initially he wanted to become a musician, but sadly the band he founded in his youth with four friends broke up.',
            active_text: 'Imprison your target. They will not be able to use their ability at night.',
            passive_text: 'This character protects its leader with his life. If the president would die, you will die instead.',
            text_success: "Someone was caught by the police and put to jail.",
            text_fail: 'Imprisoning failed')
Role.create(name: 'Officer',
            party: 'Town',
            active: 'imprison',
            passive: '',
            power: '2',
            rank: '',
            image: '/images/town/officer_town.jpg',
            goal: 'Bear down all henchmen of the mafia.',
            lore: 'She’s an incredibly loyal police woman and fulfils her duties with pride. Mercy is an unknown concept to her - even the smallest transgressions cause her gentle soul to take the backseat, while her unyielding sense of justice dishes out righteous punishment. Her secret dream is to be promoted to Chief one day – but until then she focuses on working on her bikini body.',
            punchline: 'Her secret dream is to be promoted to Chief one day – but until then she focuses on working on her bikini body.',
            active_text: 'Imprison your target. They will not be able to use their ability at night.',
            passive_text: '',
            text_success: "Someone was caught by the police and put to jail.",
            text_fail: 'Imprisoning failed')
Role.create(name: 'Agent',
            party: 'Town',
            active: 'spy',
            passive: '',
            power: '1',
            rank: '',
            image: '/images/town/agent_town.jpg',
            goal: 'Bear down all henchmen of the mafia.',
            lore: 'A very mysterious character – nobody knows their real identity nor gender. Nonetheless or probably exactly because of that, their work as secret agent is invaluable. Nobody is faster at gathering important information.',
            punchline: 'Nobody is faster at gathering important information.',
            active_text: 'Snoop on somebody to get information about a player’s character role',
            passive_text: '',
            text_success: 'Espionage has been carried out.',
            text_fail: 'Spying failed')
Role.create(name: 'Junior',
            party: 'Anarchists',
            active: 'poison',
            passive: 'immunity',
            power: '4',
            rank: '',
            image: '',
            goal: 'Poison the godfather and the president to win the game.',
            lore: 'His father is the owner of the country’s biggest newspaper firm, but despite their good social standing, Junior rebels against the current government and is generally opposed to authority and organisations, preferring instead the idea of an anarchist system. His biggest hobby is gardening, which is also why he strongly supports the legalisation of certain useful and decorative plants.',
            punchline: 'His biggest hobby is gardening, which is also why he strongly supports the legalisation of certain useful and decorative plants',
            active_text: 'Put poison in your foes’ drink. This has been their last sunset.',
            passive_text: 'This character cannot be corrupted nor converted',
            text_success: "Rats! Someone has been deadly poisoned by the anarchist.",
            text_fail: 'Poisoning failed.')